CREATE TABLE Roluri(
    id_r INT PRIMARY KEY IDENTITY,
    denumire VARCHAR(50) NOT NULL
);

CREATE TABLE Echipamente(
    id_e  INT PRIMARY KEY IDENTITY,
    tip VARCHAR(50) NOT NULL
);

CREATE TABLE Angajati(
    id_a INT PRIMARY KEY IDENTITY,
    nume VARCHAR(50) NOT NULL,
    prenume VARCHAR(50) NOT NULL,
    id_e INT FOREIGN KEY REFERENCES Echipamente(id_e) ON UPDATE CASCADE ON DELETE CASCADE,
    id_r INT FOREIGN KEY REFERENCES Roluri(id_r) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Clienti(
    id_c INT PRIMARY KEY IDENTITY,
    nume VARCHAR(50) NOT NULL,
    prenume VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    parola VARCHAR(50) NOT NULL
);

CREATE TABLE Statusuri(
    id_s INT PRIMARY KEY IDENTITY,
    puncte_penalizare INT NOT NULL,
    puncte_bonus INT NOT NULL,
    id_c INT UNIQUE FOREIGN KEY REFERENCES Clienti(id_c) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Conditii(
    id_cond INT PRIMARY KEY IDENTITY,
    stare_motor VARCHAR(50) NOT NULL,
    stare_exterior VARCHAR(50) NOT NULL,
    stare_interior VARCHAR(50) NOT NULL
);

CREATE TABLE Masini(
    cod_m INT PRIMARY KEY IDENTITY,
    marca VARCHAR(50) NOT NULL,
    model VARCHAR(50) NOT NULL,
    an INT NOT NULL,
    culoare VARCHAR(50),
    id_cond INT UNIQUE FOREIGN KEY REFERENCES Conditii(id_cond) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Categorii(
    id_cat INT PRIMARY KEY IDENTITY,
    denumire VARCHAR(50) NOT NULL
);

CREATE TABLE Masini_Categorii(
    id_cat INT FOREIGN KEY REFERENCES Categorii(id_cat) ON UPDATE CASCADE ON DELETE CASCADE,
    cod_m INT FOREIGN KEY REFERENCES Masini(cod_m) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT pk_masini_categorii PRIMARY KEY (id_cat, cod_m)
);

CREATE TABLE Inchirieri(
    id_i INT PRIMARY KEY IDENTITY,
    cod_m INT FOREIGN KEY REFERENCES Masini(cod_m) ON UPDATE CASCADE ON DELETE CASCADE,
    id_c INT FOREIGN KEY REFERENCES Clienti(id_c) ON UPDATE CASCADE ON DELETE CASCADE,
    data_start DATETIME NOT NULL,
    data_finalizare DATETIME NOT NULL,
    id_a INT FOREIGN KEY REFERENCES Angajati(id_a) ON UPDATE CASCADE ON DELETE CASCADE
);