CREATE TABLE Roles(
    id_r INT PRIMARY KEY IDENTITY,
    role_name VARCHAR(50) NOT NULL
);

CREATE TABLE Equipments(
    id_e INT PRIMARY KEY IDENTITY,
    e_type VARCHAR(50) NOT NULL
);

CREATE TABLE Employees(
    id_emp INT PRIMARY KEY IDENTITY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    id_e INT FOREIGN KEY REFERENCES Equipments(id_e) ON UPDATE CASCADE ON DELETE CASCADE,
    id_r INT FOREIGN KEY REFERENCES Roles(id_r) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Clients(
    id_c INT PRIMARY KEY IDENTITY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    client_password VARCHAR(50) NOT NULL
);

CREATE TABLE Statuses(
    id_s INT PRIMARY KEY IDENTITY,
    penalization_points INT NOT NULL,
    bonus_points INT NOT NULL,
    id_c INT UNIQUE FOREIGN KEY REFERENCES Clients(id_c) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Conditions(
    id_cond INT PRIMARY KEY IDENTITY,
    engine VARCHAR(50) NOT NULL,
    exterior VARCHAR(50) NOT NULL,
    interior VARCHAR(50) NOT NULL
);

CREATE TABLE Cars(
    id_m INT PRIMARY KEY IDENTITY,
    brand VARCHAR(50) NOT NULL,
    model VARCHAR(50) NOT NULL,
    year_of_manufacture INT NOT NULL,
    color VARCHAR(50),
    id_cond INT UNIQUE FOREIGN KEY REFERENCES Conditions(id_cond) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Categories(
    id_cat INT PRIMARY KEY IDENTITY,
    cat_name VARCHAR(50) NOT NULL
);

CREATE TABLE CombinationsOfCarsAndCategories(
    id_cat INT FOREIGN KEY REFERENCES Categories(id_cat) ON UPDATE CASCADE ON DELETE CASCADE,
    id_m INT FOREIGN KEY REFERENCES Cars(id_m) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT pk_cars_and_categories PRIMARY KEY (id_cat, id_m)
);

CREATE TABLE Rentals(
    id_rent INT PRIMARY KEY IDENTITY,
    id_m INT FOREIGN KEY REFERENCES Cars(id_m) ON UPDATE CASCADE ON DELETE CASCADE,
    id_c INT FOREIGN KEY REFERENCES Clients(id_c) ON UPDATE CASCADE ON DELETE CASCADE,
	starting_date DATETIME NOT NULL,
    end_date DATETIME NOT NULL,
    id_emp INT FOREIGN KEY REFERENCES Employees(id_emp) ON UPDATE CASCADE ON DELETE CASCADE
);